// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgdgtkbkhvmcuyatotrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnZGd0a2JraHZtY3V5YXRvdHJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMjI4NjYsImV4cCI6MjA2NjY5ODg2Nn0.ubicpCar4-YixCoTzmbblW8FZGVSGK4SatcNt833ewk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);